networks:
  app_network:
    driver: bridge

services:
  web:
    image: ${WEB_IMAGE}
    command: gunicorn {{cookiecutter.project_slug}}.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - /var/backups:/var/backups
      - ${STATICFILES_HOST}:/home/app/public/staticfiles
      - ${MEDIAFILES_HOST}:/home/app/public/mediafiles
    ports:
      - "8000:80"
    env_file:
      - .env_var
    environment:
      - DJANGO_SETTINGS_MODULE={{cookiecutter.project_slug}}.settings.production
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_var
    networks:
      - app_network

volumes:
  postgres_data:
