name: CI
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  WEB_IMAGE: backend
  MEDIAFILES_HOST: /home/public/mediafiles
  STATICFILES_HOST: /home/public/staticfiles

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Coookiecutter the project and run tests on web image
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./onewordnointerpunction/backend

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4

    - name: Set up Python to run cookiecutter
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: false

    - name: Run cookiecutter on repo
      working-directory: ./
      run: |
        uv pip install cookiecutter --system
        cookiecutter gh:marcelhekking/cookiecutter-drf --checkout $BRANCH_NAME --no-input

    - name: Make uv lock file and Build image
      run: |
        uv lock
        docker build -t ${{ env.WEB_IMAGE }}:latest -f Dockerfile .

    - name: Define a cache dependency glob
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml

    - name: Test web image
      run: |
        docker compose -p ${{ env.WEB_IMAGE }} -f docker-compose.yml run --rm web sh -c "python -m pytest ../tests/"
